name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: git add dist && git commit -m "build"
      - run: git subtree push --prefix dist origin gh-pages

