name: Build and Deploy

on:
  push:
    branches:
      - master

  pull_request:
    types: [closed]
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages
          git add dist
          git commit -m "Build"
          git push origin `git subtree split --prefix dist master`:gh-pages --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
