name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version
        run: nvm use 18 && npm --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages
          git add dist
          git commit -m "Build"
          git subtree push --prefix dist origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
