name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          - npm install
          - npm run build
      - name: deploy
        run: |
          - git add dist && git commit -m "build"
          - git subtree push --prefix dist origin gh-pages
