name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - name: Login to GH Packages
      - uses: fregante/setup-git-user@v2
      - name: Configure Git user
      - run: |
          git config user.name "${{ github.user.login }}"
          git config user.email "${{ github.user.email }}"
          git add dist && git commit -m "build"
          git subtree push --prefix dist origin gh-pages

