name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v14.17.6
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'
      - name: build
        run: |
          - export NVM_DIR=~/.nvm
          - source ~/.nvm/nvm.sh
          - npm install
          - npm run build
      - name: deploy
        run: |
          - git add dist && git commit -m "build"
          - git subtree push --prefix dist origin gh-pages
